from typing import List, Dict, Any, Optional
from datetime import datetime
import logging
from app.core.database import db
from app.core.exceptions import NotFoundError, ValidationError

logger = logging.getLogger(__name__)

class QuestionService:
    """Question bank management service"""
    
    async def get_next_question_id(self) -> int:
        """Get the next available numeric question ID"""
        try:
            # Query for the highest question_id in the questions collection
            questions = await db.query_collection(
                "questions",
                filters=[],
                limit=1,
                order_by="-question_id"  # Get the highest question_id
            )

            if questions and questions[0].get("question_id") is not None:
                next_id = int(questions[0]["question_id"]) + 1
            else:
                next_id = 1  # Start from 1 if no questions exist

            return next_id

        except Exception as e:
            logger.error(f"Failed to get next question ID: {e}")
            raise

    async def get_question_by_question_id(self, question_id: int) -> Optional[Dict[str, Any]]:
        """Get a question by its numeric question_id"""
        try:
            questions = await db.query_collection(
                "questions",
                filters=[
                    {"field": "question_id", "operator": "==", "value": question_id},
                    {"field": "is_active", "operator": "==", "value": True}
                ],
                limit=1
            )

            return questions[0] if questions else None

        except Exception as e:
            logger.error(f"Failed to get question by question_id {question_id}: {e}")
            return None

    async def create_question(
        self,
        question_data: Dict[str, Any],
        created_by: str,
        question_id: Optional[int] = None
    ) -> str:
        """Create a new question"""
        try:
            # Validate required fields
            required_fields = [
                "question_text", "options", "correct_answer",
                "exam_type", "subject", "topic", "difficulty"
            ]

            # Ensure correct_answer is a list
            if isinstance(question_data.get("correct_answer"), str):
                question_data["correct_answer"] = [question_data["correct_answer"]]

            for field in required_fields:
                if field not in question_data:
                    raise ValidationError(f"Missing required field: {field}")

            # If question_id is provided, check if it already exists
            if question_id is not None:
                existing = await self.get_question_by_question_id(question_id)
                if existing:
                    raise ValidationError(f"Question with question_id {question_id} already exists")

            # Prepare question document
            question = {
                **question_data,
                "created_by": created_by,
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
                "is_active": True,
                "approval_status": "pending",
                "historical_frequency": question_data.get("historical_frequency", 0),
                "variations": []
            }

            # Set question_id if provided, otherwise it will be auto-generated by Firestore
            if question_id is not None:
                question["question_id"] = question_id

            firestore_question_id = await db.create_document("questions", question)

            logger.info(f"Question created: {firestore_question_id} with question_id: {question_id}")
            return firestore_question_id

        except Exception as e:
            logger.error(f"Failed to create question: {e}")
            raise

    async def update_question(
        self,
        question_id: str,
        question_data: Dict[str, Any],
        updated_by: str
    ) -> str:
        """Update an existing question"""
        try:
            # Get the existing question
            existing_question = await self.get_question(question_id)
            if not existing_question:
                raise NotFoundError("Question not found")

            # Ensure correct_answer is a list
            if isinstance(question_data.get("correct_answer"), str):
                question_data["correct_answer"] = [question_data["correct_answer"]]

            # Prepare update data
            update_data = {
                **question_data,
                "updated_at": datetime.utcnow(),
                "updated_by": updated_by
            }

            # Don't allow changing question_id once set
            if "question_id" in update_data and update_data["question_id"] != existing_question.get("question_id"):
                # Check if the new question_id is already taken by another question
                if update_data["question_id"] is not None:
                    existing_with_new_id = await self.get_question_by_question_id(update_data["question_id"])
                    if existing_with_new_id and existing_with_new_id["id"] != question_id:
                        raise ValidationError(f"Question with question_id {update_data['question_id']} already exists")

            await db.update_document("questions", question_id, update_data)

            logger.info(f"Question updated: {question_id}")
            return question_id

        except Exception as e:
            logger.error(f"Failed to update question {question_id}: {e}")
            raise
    
    async def get_question(self, question_id: str) -> Optional[Dict[str, Any]]:
        """Get a question by ID"""
        try:
            question = await db.get_document("questions", question_id)
            
            if not question or not question.get("is_active", True):
                return None
            
            return question
            
        except Exception as e:
            logger.error(f"Failed to get question {question_id}: {e}")
            return None
    
    async def get_filtered_questions(
        self,
        exam_categories: Optional[List[str]] = None,
        subjects: Optional[List[str]] = None,
        topics: Optional[List[str]] = None,
        difficulties: Optional[List[str]] = None,
        question_types: Optional[List[str]] = None,
        arde_probabilities: Optional[List[str]] = None,
        search_query: Optional[str] = None,
        tags: Optional[List[str]] = None,
        limit: int = 20,
        offset: int = 0
    ) -> List[Dict[str, Any]]:
        """Get filtered questions for question bank management with pagination"""
        try:
            filters = [
                {"field": "is_active", "operator": "==", "value": True}
            ]

            # Add filters
            if exam_categories and len(exam_categories) > 0:
                filters.append({"field": "exam_type", "operator": "in", "value": exam_categories})
            if subjects and len(subjects) > 0:
                filters.append({"field": "subject", "operator": "in", "value": subjects})
            if topics and len(topics) > 0:
                filters.append({"field": "topic", "operator": "in", "value": topics})
            if difficulties and len(difficulties) > 0:
                filters.append({"field": "difficulty", "operator": "in", "value": difficulties})
            if question_types and len(question_types) > 0:
                filters.append({"field": "question_type", "operator": "in", "value": question_types})
            if arde_probabilities and len(arde_probabilities) > 0:
                # Convert enum values to decimal ranges for filtering
                decimal_ranges = []
                for prob in arde_probabilities:
                    if prob == "low":
                        # Low: 0.0 to 0.3
                        decimal_ranges.extend([0.0, 0.1, 0.2, 0.3])
                    elif prob == "medium":
                        # Medium: 0.3 to 0.7
                        decimal_ranges.extend([0.3, 0.4, 0.5, 0.6, 0.7])
                    elif prob == "high":
                        # High: 0.7 to 1.0
                        decimal_ranges.extend([0.7, 0.8, 0.9, 1.0])

                if decimal_ranges:
                    # Use multiple OR conditions for decimal ranges
                    # This is a simplified approach - in production you might want more sophisticated range queries
                    filters.append({"field": "arde_probability", "operator": "in", "value": list(set(decimal_ranges))})
            if tags and len(tags) > 0:
                # For tags, we need to check if any of the question's tags match
                # This is more complex, we'll handle it in post-processing
                pass

            # Temporarily simplify query to avoid index requirements for development
            # TODO: Create proper Firestore indexes for production
            try:
                questions = await db.query_collection(
                    "questions",
                    filters=filters,
                    limit=limit,
                    offset=offset,
                    order_by="-created_at"
                )
            except Exception as index_error:
                logger.warning(f"Index error, falling back to simple query: {index_error}")
                # Fallback: Get all questions without any filters or ordering (for development only)
                try:
                    questions = await db.query_collection(
                        "questions",
                        filters=[],  # No filters
                        limit=limit * 2
                    )
                    # Filter active questions in memory
                    questions = [q for q in questions if q.get("is_active", True)]
                    # Sort in memory and apply offset
                    questions.sort(key=lambda x: x.get("created_at", datetime.min), reverse=True)
                    questions = questions[offset:offset + limit]
                except Exception as fallback_error:
                    logger.error(f"Fallback query also failed: {fallback_error}")
                    # Last resort: Get documents directly (this will be slow but works)
                    questions = []
                    # This is a temporary development workaround
                    # In production, proper indexes should be created

            # Filter by tags if specified (post-processing)
            if tags and len(tags) > 0:
                questions = [
                    q for q in questions
                    if any(tag in q.get("tags", []) for tag in tags)
                ]

            # Filter by search query if specified
            if search_query and search_query.strip():
                query_lower = search_query.lower()
                questions = [
                    q for q in questions
                    if query_lower in q.get("question_text", "").lower() or
                       query_lower in q.get("subject", "").lower() or
                       query_lower in q.get("topic", "").lower() or
                       any(query_lower in tag for tag in q.get("tags", []))
                ]

            # Add creator names and set default values for missing approval workflow fields
            for question in questions:
                creator_id = question.get("created_by")
                if creator_id:
                    user = await db.get_document("users", creator_id)
                    if user and user.get("profile"):
                        question["created_by_name"] = user["profile"].get("name", "Unknown")
                    else:
                        question["created_by_name"] = "Unknown"
                else:
                    question["created_by_name"] = "Unknown"

                # Set default values for approval workflow fields if missing
                if "submitted_at" not in question or question["submitted_at"] is None:
                    question["submitted_at"] = question.get("created_at")
                if "status" not in question:
                    question["status"] = "pending"
                if "reviewer_id" not in question:
                    question["reviewer_id"] = None
                if "reviewer_name" not in question:
                    question["reviewer_name"] = None
                if "review_comments" not in question:
                    question["review_comments"] = None
                if "reviewed_at" not in question:
                    question["reviewed_at"] = None
                if "approved_at" not in question:
                    question["approved_at"] = None

            return questions

        except Exception as e:
            logger.error(f"Failed to get filtered questions: {e}")
            return []

    async def get_questions_for_practice(
        self,
        exam_type: str,
        subject: Optional[str] = None,
        topic: Optional[str] = None,
        difficulty: Optional[str] = None,
        arde_probability: Optional[str] = None,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Get questions for practice session"""
        try:
            filters = [
                {"field": "exam_type", "operator": "==", "value": exam_type},
                {"field": "is_active", "operator": "==", "value": True},
                {"field": "approval_status", "operator": "==", "value": "approved"}
            ]
            
            # Add optional filters
            if subject:
                filters.append({"field": "subject", "operator": "==", "value": subject})
            if topic:
                filters.append({"field": "topic", "operator": "==", "value": topic})
            if difficulty:
                filters.append({"field": "difficulty", "operator": "==", "value": difficulty})
            if arde_probability:
                # Convert enum value to decimal range for filtering
                if arde_probability == "low":
                    # Filter for arde_probability between 0.0 and 0.3
                    filters.append({"field": "arde_probability", "operator": ">=", "value": 0.0})
                    filters.append({"field": "arde_probability", "operator": "<=", "value": 0.3})
                elif arde_probability == "medium":
                    # Filter for arde_probability between 0.3 and 0.7
                    filters.append({"field": "arde_probability", "operator": ">", "value": 0.3})
                    filters.append({"field": "arde_probability", "operator": "<=", "value": 0.7})
                elif arde_probability == "high":
                    # Filter for arde_probability between 0.7 and 1.0
                    filters.append({"field": "arde_probability", "operator": ">", "value": 0.7})
                    filters.append({"field": "arde_probability", "operator": "<=", "value": 1.0})
            
            questions = await db.query_collection(
                "questions",
                filters=filters,
                limit=limit,
                order_by="-created_at"
            )

            # Add creator names before removing sensitive info
            for question in questions:
                creator_id = question.get("created_by")
                if creator_id:
                    user = await db.get_document("users", creator_id)
                    if user and user.get("profile"):
                        question["created_by_name"] = user["profile"].get("name", "Unknown")
                    else:
                        question["created_by_name"] = "Unknown"
                else:
                    question["created_by_name"] = "Unknown"

            # Remove sensitive information for practice
            for question in questions:
                question.pop("created_by", None)
                question.pop("approval_status", None)

            return questions
            
        except Exception as e:
            logger.error(f"Failed to get practice questions: {e}")
            return []
    
    async def get_questions_for_exam(
        self,
        exam_type: str,
        question_count: int,
        arde_priority: bool = True
    ) -> List[Dict[str, Any]]:
        """Get questions for simulated exam"""
        try:
            filters = [
                {"field": "exam_type", "operator": "==", "value": exam_type},
                {"field": "is_active", "operator": "==", "value": True},
                {"field": "approval_status", "operator": "==", "value": "approved"}
            ]
            
            if arde_priority:
                # Prioritize high ARDE probability questions (0.7-1.0 range)
                filters.append({"field": "arde_probability", "operator": ">=", "value": 0.7})
                filters.append({"field": "arde_probability", "operator": "<=", "value": 1.0})
                
                high_arde_questions = await db.query_collection(
                    "questions",
                    filters=filters,
                    limit=question_count // 2
                )
                
                # Get remaining questions from medium/low ARDE
                remaining_count = question_count - len(high_arde_questions)
                
                if remaining_count > 0:
                    # Get medium and low probability questions (0.0-0.7 range)
                    medium_low_filters = filters[:-2]  # Remove the high probability filters
                    medium_low_filters.extend([
                        {"field": "arde_probability", "operator": ">=", "value": 0.0},
                        {"field": "arde_probability", "operator": "<=", "value": 0.7}
                    ])
                    other_questions = await db.query_collection(
                        "questions",
                        filters=medium_low_filters,
                        limit=remaining_count
                    )
                    questions = high_arde_questions + other_questions
                else:
                    questions = high_arde_questions
            else:
                # Random selection
                questions = await db.query_collection(
                    "questions",
                    filters=filters,
                    limit=question_count
                )
            
            # Add creator names before removing sensitive info
            for question in questions:
                creator_id = question.get("created_by")
                if creator_id:
                    user = await db.get_document("users", creator_id)
                    if user and user.get("profile"):
                        question["created_by_name"] = user["profile"].get("name", "Unknown")
                    else:
                        question["created_by_name"] = "Unknown"
                else:
                    question["created_by_name"] = "Unknown"

            # Remove sensitive information
            for question in questions:
                question.pop("created_by", None)
                question.pop("approval_status", None)

            return questions[:question_count]  # Ensure exact count
            
        except Exception as e:
            logger.error(f"Failed to get exam questions: {e}")
            return []
    
    async def record_question_attempt(
        self,
        question_id: str,
        user_id: str,
        is_correct: bool,
        time_taken: float
    ) -> bool:
        """Record a question attempt for analytics"""
        try:
            # Record individual attempt
            attempt_data = {
                "question_id": question_id,
                "user_id": user_id,
                "is_correct": is_correct,
                "time_taken": time_taken,
                "attempted_at": datetime.utcnow()
            }
            
            await db.create_document("question_attempts", attempt_data)
            
            # Note: Performance stats are now calculated from question_attempts collection
            # No need to update question document with performance stats
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to record question attempt: {e}")
            return False
    
    async def get_question_explanation(
        self,
        question_id: str,
        user_id: str
    ) -> Optional[Dict[str, Any]]:
        """Get question explanation (subject to user limits)"""
        try:
            question = await self.get_question(question_id)
            
            if not question:
                raise NotFoundError("Question not found")
            
            # Check if explanation exists
            explanation = question.get("explanation", {})
            
            if not explanation:
                return None
            
            # Record explanation usage
            usage_data = {
                "question_id": question_id,
                "user_id": user_id,
                "accessed_at": datetime.utcnow()
            }
            
            await db.create_document("explanation_usage", usage_data)
            
            return {
                "question_id": question_id,
                "explanation": explanation,
                "references": question.get("references", []),
                "video_url": question.get("video_explanation_url"),
                "arde_context": question.get("arde_context")
            }
            
        except Exception as e:
            logger.error(f"Failed to get question explanation: {e}")
            return None
    
    async def update_question_arde_data(
        self,
        question_id: str,
        arde_probability: str,
        historical_frequency: int,
        arde_context: Optional[str] = None
    ) -> bool:
        """Update ARDE probability data for a question"""
        try:
            update_data = {
                "arde_probability": arde_probability,
                "historical_frequency": historical_frequency,
                "updated_at": datetime.utcnow()
            }

            if arde_context:
                update_data["arde_context"] = arde_context

            await db.update_document("questions", question_id, update_data)

            logger.info(f"ARDE data updated for question: {question_id}")
            return True

        except Exception as e:
            logger.error(f"Failed to update ARDE data: {e}")
            return False

    # Approval Workflow Methods

    async def get_pending_questions(
        self,
        exam_type: Optional[str] = None,
        subject: Optional[str] = None,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Get questions pending approval"""
        try:
            filters = [
                {"field": "is_active", "operator": "==", "value": True},
                {"field": "approval_status", "operator": "==", "value": "pending"}
            ]

            if exam_type:
                filters.append({"field": "exam_type", "operator": "==", "value": exam_type})
            if subject:
                filters.append({"field": "subject", "operator": "==", "value": subject})

            questions = await db.query_collection(
                "questions",
                filters=filters,
                limit=limit,
                order_by="created_at"
            )

            # Add creator names
            for question in questions:
                creator_id = question.get("created_by")
                if creator_id:
                    user = await db.get_document("users", creator_id)
                    if user and user.get("profile"):
                        question["created_by_name"] = user["profile"].get("name", "Unknown")
                    else:
                        question["created_by_name"] = "Unknown"

            return questions

        except Exception as e:
            logger.error(f"Failed to get pending questions: {e}")
            return []

    async def approve_question(
        self,
        question_id: str,
        reviewer_id: str,
        reviewer_name: str,
        action: str,
        comments: Optional[str] = None
    ) -> Dict[str, Any]:
        """Approve or reject a question"""
        try:
            # Get the question first
            question = await self.get_question(question_id)
            if not question:
                raise NotFoundError("Question not found")

            # Determine new status
            new_status = "approved" if action == "approve" else "rejected"

            # Prepare update data
            update_data = {
                "approval_status": new_status,
                "reviewer_id": reviewer_id,
                "reviewer_name": reviewer_name,
                "reviewed_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            }

            if comments:
                update_data["review_comments"] = comments

            if action == "approve":
                update_data["approved_at"] = datetime.utcnow()

            # Update the question
            await db.update_document("questions", question_id, update_data)

            # Log the approval action
            audit_data = {
                "question_id": question_id,
                "reviewer_id": reviewer_id,
                "action": action,
                "comments": comments,
                "timestamp": datetime.utcnow(),
                "question_creator": question.get("created_by")
            }
            await db.create_document("question_approvals", audit_data)

            logger.info(f"Question {question_id} {action}d by {reviewer_name}")

            return {
                "question_id": question_id,
                "status": new_status,
                "reviewer_id": reviewer_id,
                "reviewer_name": reviewer_name,
                "reviewed_at": update_data["reviewed_at"],
                "comments": comments
            }

        except Exception as e:
            logger.error(f"Failed to approve question: {e}")
            raise

    async def bulk_approve_questions(
        self,
        question_ids: List[str],
        reviewer_id: str,
        reviewer_name: str,
        action: str,
        comments: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Bulk approve or reject multiple questions"""
        try:
            results = []

            for question_id in question_ids:
                try:
                    result = await self.approve_question(
                        question_id=question_id,
                        reviewer_id=reviewer_id,
                        reviewer_name=reviewer_name,
                        action=action,
                        comments=comments
                    )
                    results.append(result)
                except Exception as e:
                    logger.error(f"Failed to process question {question_id}: {e}")
                    # Continue with other questions even if one fails
                    continue

            logger.info(f"Bulk {action} completed: {len(results)}/{len(question_ids)} questions processed")
            return results

        except Exception as e:
            logger.error(f"Failed to bulk approve questions: {e}")
            raise

    async def get_user_submissions(
        self,
        user_id: str,
        status: Optional[str] = None,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Get user's question submissions with workflow status"""
        try:
            filters = [
                {"field": "created_by", "operator": "==", "value": user_id},
                {"field": "is_active", "operator": "==", "value": True}
            ]

            if status:
                filters.append({"field": "approval_status", "operator": "==", "value": status})

            submissions = await db.query_collection(
                "questions",
                filters=filters,
                limit=limit,
                order_by="-created_at"
            )

            # Format for workflow status response
            workflow_submissions = []
            for submission in submissions:
                workflow_submissions.append({
                    "question_id": submission["id"],
                    "status": submission.get("approval_status", "pending"),
                    "created_by": submission["created_by"],
                    "submitted_at": submission["created_at"],
                    "reviewer_id": submission.get("reviewer_id"),
                    "reviewer_name": submission.get("reviewer_name"),
                    "reviewed_at": submission.get("reviewed_at"),
                    "comments": submission.get("review_comments")
                })

            return workflow_submissions

        except Exception as e:
            logger.error(f"Failed to get user submissions: {e}")
            return []

    async def get_review_stats(self, reviewer_id: str) -> Dict[str, Any]:
        """Get review statistics for a reviewer"""
        try:
            # Get total reviews by this reviewer
            total_reviews = await db.query_collection(
                "question_approvals",
                filters=[{"field": "reviewer_id", "operator": "==", "value": reviewer_id}]
            )

            # Count approvals and rejections
            approved_count = sum(1 for review in total_reviews if review["action"] == "approve")
            rejected_count = sum(1 for review in total_reviews if review["action"] == "reject")

            # Get pending questions count
            pending_questions = await self.get_pending_questions(limit=1000)
            pending_count = len(pending_questions)

            # Get recent activity (last 30 days)
            thirty_days_ago = datetime.utcnow().replace(day=datetime.utcnow().day - 30)
            recent_reviews = [
                review for review in total_reviews
                if review["timestamp"] > thirty_days_ago
            ]

            return {
                "total_reviews": len(total_reviews),
                "approved_count": approved_count,
                "rejected_count": rejected_count,
                "pending_questions": pending_count,
                "recent_activity": len(recent_reviews),
                "approval_rate": (approved_count / len(total_reviews) * 100) if total_reviews else 0
            }

        except Exception as e:
            logger.error(f"Failed to get review stats: {e}")
            return {
                "total_reviews": 0,
                "approved_count": 0,
                "rejected_count": 0,
                "pending_questions": 0,
                "recent_activity": 0,
                "approval_rate": 0
            }

# Global question service instance
question_service = QuestionService()