// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqPvFmXSNCCCwcHcejMInjExSrbDXtek',
    appId: '1:13539990837:web:b96dde32c8c0948a3d407c',
    messagingSenderId: '13539990837',
    projectId: 'entrytestguru-dev',
    authDomain: 'entrytestguru-dev.firebaseapp.com',
    storageBucket: 'entrytestguru-dev.firebasestorage.app',
    measurementId: 'G-R12LPL8XWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTqPvFmXSNCCCwcHcejMInjExSrbDXtek',
    appId: '1:13539990837:android:PLACEHOLDER',
    messagingSenderId: '13539990837',
    projectId: 'entrytestguru-dev',
    storageBucket: 'entrytestguru-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqPvFmXSNCCCwcHcejMInjExSrbDXtek',
    appId: '1:13539990837:ios:PLACEHOLDER',
    messagingSenderId: '13539990837',
    projectId: 'entrytestguru-dev',
    storageBucket: 'entrytestguru-dev.firebasestorage.app',
    iosBundleId: 'com.entrytestguru.entrytestguru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqPvFmXSNCCCwcHcejMInjExSrbDXtek',
    appId: '1:13539990837:ios:PLACEHOLDER',
    messagingSenderId: '13539990837',
    projectId: 'entrytestguru-dev',
    storageBucket: 'entrytestguru-dev.firebasestorage.app',
    iosBundleId: 'com.entrytestguru.entrytestguru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqPvFmXSNCCCwcHcejMInjExSrbDXtek',
    appId: '1:13539990837:web:b96dde32c8c0948a3d407c',
    messagingSenderId: '13539990837',
    projectId: 'entrytestguru-dev',
    authDomain: 'entrytestguru-dev.firebaseapp.com',
    storageBucket: 'entrytestguru-dev.firebasestorage.app',
    measurementId: 'G-R12LPL8XWT',
  );
}