// Mocks generated by Mockito 5.4.6 from annotations
// in entrytestguru/test/features/questions/presentation/widgets/add_question_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:entrytestguru/features/questions/data/models/question.dart'
    as _i4;
import 'package:entrytestguru/features/questions/data/models/question_attempt.dart'
    as _i6;
import 'package:entrytestguru/features/questions/data/models/question_filter.dart'
    as _i5;
import 'package:entrytestguru/features/questions/data/services/question_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuestionApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionApiService extends _i1.Mock
    implements _i2.QuestionApiService {
  MockQuestionApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Question>> getFilteredQuestions(
    _i5.QuestionFilter? filter, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFilteredQuestions,
              [filter],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<_i4.Question?> getQuestion(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestion, [questionId]),
            returnValue: _i3.Future<_i4.Question?>.value(),
          )
          as _i3.Future<_i4.Question?>);

  @override
  _i3.Future<List<_i4.Question>> searchQuestions(
    String? query, {
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchQuestions,
              [query],
              {#examCategory: examCategory, #limit: limit},
            ),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsForPractice({
    required String? examCategory,
    String? subject,
    String? topic,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsForPractice, [], {
              #examCategory: examCategory,
              #subject: subject,
              #topic: topic,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsForExam({
    required String? examCategory,
    int? questionCount = 100,
    bool? prioritizeHighArde = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsForExam, [], {
              #examCategory: examCategory,
              #questionCount: questionCount,
              #prioritizeHighArde: prioritizeHighArde,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<void> recordAttempt(_i6.QuestionAttempt? attempt) =>
      (super.noSuchMethod(
            Invocation.method(#recordAttempt, [attempt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.QuestionAttempt>> getQuestionAttempts(
    String? questionId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getQuestionAttempts,
              [questionId],
              {#userId: userId},
            ),
            returnValue: _i3.Future<List<_i6.QuestionAttempt>>.value(
              <_i6.QuestionAttempt>[],
            ),
          )
          as _i3.Future<List<_i6.QuestionAttempt>>);

  @override
  _i3.Future<List<_i6.QuestionAttempt>> getSessionAttempts(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionAttempts, [sessionId]),
            returnValue: _i3.Future<List<_i6.QuestionAttempt>>.value(
              <_i6.QuestionAttempt>[],
            ),
          )
          as _i3.Future<List<_i6.QuestionAttempt>>);

  @override
  _i3.Future<void> toggleBookmark(String? questionId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [questionId], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Question>> getBookmarkedQuestions({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedQuestions, [], {#userId: userId}),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<void> addQuestionNote(
    String? questionId,
    String? note, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addQuestionNote,
              [questionId, note],
              {#userId: userId},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Question>> getWeakAreaQuestions({
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWeakAreaQuestions, [], {
              #examCategory: examCategory,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getUnattemptedQuestions({
    String? examCategory,
    String? subject,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnattemptedQuestions, [], {
              #examCategory: examCategory,
              #subject: subject,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<List<_i4.Question>> getHighArdeQuestions({
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHighArdeQuestions, [], {
              #examCategory: examCategory,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<Map<String, dynamic>> getQuestionStats(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionStats, [questionId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> upgradeAnonymousToRegistered({
    required String? email,
    required String? password,
    required String? examType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeAnonymousToRegistered, [], {
              #email: email,
              #password: password,
              #examType: examType,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> upgradeToProTier(String? paymentToken) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeToProTier, [paymentToken]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getSubscriptionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionStatus, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getUsageLimits() =>
      (super.noSuchMethod(
            Invocation.method(#getUsageLimits, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
