// Mocks generated by Mockito 5.4.6 from annotations
// in entrytestguru/test/features/questions/presentation/widgets/add_question_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:entrytestguru/features/questions/data/models/question.dart'
    as _i2;
import 'package:entrytestguru/features/questions/data/models/question_attempt.dart'
    as _i7;
import 'package:entrytestguru/features/questions/data/models/question_create_request.dart'
    as _i6;
import 'package:entrytestguru/features/questions/data/models/question_filter.dart'
    as _i5;
import 'package:entrytestguru/features/questions/data/services/question_api_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuestion_0 extends _i1.SmartFake implements _i2.Question {
  _FakeQuestion_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuestionApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionApiService extends _i1.Mock
    implements _i3.QuestionApiService {
  MockQuestionApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Question>> getFilteredQuestions(
    _i5.QuestionFilter? filter, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFilteredQuestions,
              [filter],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<_i2.Question?> getQuestion(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestion, [questionId]),
            returnValue: _i4.Future<_i2.Question?>.value(),
          )
          as _i4.Future<_i2.Question?>);

  @override
  _i4.Future<_i2.Question> createQuestion(_i6.QuestionCreateRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createQuestion, [request]),
            returnValue: _i4.Future<_i2.Question>.value(
              _FakeQuestion_0(
                this,
                Invocation.method(#createQuestion, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Question>);

  @override
  _i4.Future<List<_i2.Question>> searchQuestions(
    String? query, {
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchQuestions,
              [query],
              {#examCategory: examCategory, #limit: limit},
            ),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<List<_i2.Question>> getQuestionsForPractice({
    required String? examCategory,
    String? subject,
    String? topic,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsForPractice, [], {
              #examCategory: examCategory,
              #subject: subject,
              #topic: topic,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<List<_i2.Question>> getQuestionsForExam({
    required String? examCategory,
    int? questionCount = 100,
    bool? prioritizeHighArde = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsForExam, [], {
              #examCategory: examCategory,
              #questionCount: questionCount,
              #prioritizeHighArde: prioritizeHighArde,
            }),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<void> recordAttempt(_i7.QuestionAttempt? attempt) =>
      (super.noSuchMethod(
            Invocation.method(#recordAttempt, [attempt]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.QuestionAttempt>> getQuestionAttempts(
    String? questionId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getQuestionAttempts,
              [questionId],
              {#userId: userId},
            ),
            returnValue: _i4.Future<List<_i7.QuestionAttempt>>.value(
              <_i7.QuestionAttempt>[],
            ),
          )
          as _i4.Future<List<_i7.QuestionAttempt>>);

  @override
  _i4.Future<List<_i7.QuestionAttempt>> getSessionAttempts(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionAttempts, [sessionId]),
            returnValue: _i4.Future<List<_i7.QuestionAttempt>>.value(
              <_i7.QuestionAttempt>[],
            ),
          )
          as _i4.Future<List<_i7.QuestionAttempt>>);

  @override
  _i4.Future<void> toggleBookmark(String? questionId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [questionId], {#userId: userId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Question>> getBookmarkedQuestions({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedQuestions, [], {#userId: userId}),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<void> addQuestionNote(
    String? questionId,
    String? note, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addQuestionNote,
              [questionId, note],
              {#userId: userId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Question>> getWeakAreaQuestions({
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWeakAreaQuestions, [], {
              #examCategory: examCategory,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<List<_i2.Question>> getUnattemptedQuestions({
    String? examCategory,
    String? subject,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnattemptedQuestions, [], {
              #examCategory: examCategory,
              #subject: subject,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<List<_i2.Question>> getHighArdeQuestions({
    String? examCategory,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHighArdeQuestions, [], {
              #examCategory: examCategory,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Question>>.value(<_i2.Question>[]),
          )
          as _i4.Future<List<_i2.Question>>);

  @override
  _i4.Future<Map<String, dynamic>> getQuestionStats(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionStats, [questionId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<int> getTotalQuestionCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalQuestionCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
